default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: exp-tracker_dev

test:
  <<: *default
  database: exp-tracker_test

production:
  <<: *default
  database: exp-tracker_prod
 
